### ISSUE TITLE
Warning is treated as an error

### ISSUE THREAD

**Issue by 0x0badc0de** [zrrrzzt/tfk-api-unoconv#125]
Most of files are converted just fine but for some of them following appears in logs:
```
unoconv_1  | Error:
unoconv_1  |    Accessibility Warning:
unoconv_1  |             No alternate text ('svg:title' element) set for
unoconv_1  |             image '
unoconv_1  |                                                    '!
unoconv_1  |
unoconv_1  |
unoconv_1  |     at ChildProcess.<anonymous> (/unoconvservice/node_modules/unoconv2/index.js:58:29)
unoconv_1  |     at emitTwo (events.js:126:13)
unoconv_1  |     at ChildProcess.emit (events.js:214:7)
unoconv_1  |     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
unoconv_1  | /unoconvservice/uploads/9c0d3ee2-d462-4912-b023-f2858df0f90d.docx deleted
```
Resulting in response
```
{"statusCode":500,"error":"Internal Server Error","message":"An internal server error occurred"}
```
If I attach to `unoconv` container and run `unoconv` command manually - the doc in question is converted as expected.

**Comment by 0x0badc0de** [comment]
Can be some kind of race condition. Set up on another machine is able to handle this file regardless the warning
```
unoconv_1  |
unoconv_1  |    Accessibility Warning:
unoconv_1  |             No alternate text ('svg:title' element) set for
unoconv_1  |             image '
unoconv_1  |                                                    '!
unoconv_1  |
unoconv_1  | finished converting
unoconv_1  | /unoconvservice/uploads/2426af4f-a1da-4b4c-b301-85ef0db9c2e9.docx deleted
```

**Comment by zrrrzzt** [comment]
There might be a timeout involved. You can try to change the [environment variables](https://github.com/zrrrzzt/tfk-api-unoconv#environment) on your first machine.

**Comment by zrrrzzt** [comment]
Thx for reporting back
