### ISSUE TITLE
TypeError: Uncaught error: Cannot read property 'filename' of undefined

### ISSUE THREAD

**Issue by linstantnoodles** [zrrrzzt/tfk-api-unoconv#57]
Hey there! I'm trying to convert a local docx file by running the following command:

```curl --form file=letter.docx http://localhost/unoconv/pdf > myfile.pdf```

It's producing this error in the container logs:

```Server running at: http://fcc6bbc68b86:3000
Debug: internal, implementation, error
    TypeError: Uncaught error: Cannot read property 'filename' of undefined
    at module.exports.handleUpload.file.on.data.file.on (/src/handlers/index.js:13:37)
    at Object.exports.execute.internals.prerequisites.internals.handler.finalize [as handler] (/src/node_modules/hapi/lib/handler.js:101:51)
    at /src/node_modules/hapi/lib/handler.js:32:23
    at internals.Protect.run.finish [as run] (/src/node_modules/hapi/lib/protect.js:59:12)
    at exports.execute.finalize (/src/node_modules/hapi/lib/handler.js:26:22)
    at each (/src/node_modules/hapi/lib/request.js:404:16)
    at iterate (/src/node_modules/hapi/node_modules/items/lib/index.js:36:13)
    at done (/src/node_modules/hapi/node_modules/items/lib/index.js:28:25)
    at internals.Auth.test.internals.Auth.payload.finalize (/src/node_modules/hapi/lib/auth.js:235:16)
    at each (/src/node_modules/hapi/lib/request.js:404:16)```

**Comment by zrrrzzt** [comment]
It seems like you are missing an ```@```in your command.

Try ```curl --form file=@letter.docx http://localhost/unoconv/pdf > myfile.pdf```

**Comment by linstantnoodles** [comment]
@zrrrzzt Yeah I just caught that haha. Thank you!!!
