### ISSUE TITLE
Error on some of the files

### ISSUE THREAD

**Issue by daneshka** [zrrrzzt/tfk-api-unoconv#87]
For some of the files that worked before, now I have this error.
Do you know what could be the problem?

(libreoffice:28): GStreamer-CRITICAL **: gst_element_link_pads_full: assertion 'GST_IS_ELEMENT (dest)' failed
2017-11-06T15:55:30.259410500Z 
    at ChildProcess.<anonymous> (/unoconvservice/node_modules/unoconv2/index.js:58:29)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
/unoconvservice/uploads/f672bbbb-a121-4209-9512-8a734bff2cfe.pptx deleted

**Comment by jivenhui** [comment]
Has this issue been resolved?
